name: CMake with Ninja and GLFW

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@latest

        #- name: Install dependencies
        #run: sudo apt-get install -y libglfw3-dev wayland-protocols wayland libwayland-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}\build --preset=debug

      - name: Build
        run: cmake --build ${{github.workspace}}\build --preset=debug

      - name: Test
        working-directory: ${{github.workspace}}\build
        run: ctest -V
