name: Windows Debug Build & Tests

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc, mingw, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup OpenGL Drivers
        uses: ssciwr/setup-mesa-dist-win@v2

      - name: Setup MinGW
        if: matrix.compiler == 'mingw'
        uses: egor-tensin/setup-mingw@v2

      - name: Setup Clang
        if: matrix.compiler == 'mingw'
        uses: egor-tensin/setup-mingw@v2

      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Configure MinGW CMake
        run: cmake --preset=test

      - name: Build
        run: cmake --build --preset=debug -- /maxcpucount

      - name: Test
        working-directory: ${{github.workspace}}/build/debug
        run: ctest --extra-verbose -C Debug -L CLI
