name: Windows Debug Build & Tests

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [msvc, mingw, clang]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup OpenGL Drivers
        uses: ssciwr/setup-mesa-dist-win@v2

      - name: Setup MinGW
        id: setup_mingw
        if: matrix.compiler == 'mingw'
        uses: egor-tensin/setup-mingw@v2
        with:
          cc: 0
          static: 0

      - name: Setup Clang
        id: setup_clang
        if: matrix.compiler == 'clang'
        uses: egor-tensin/setup-clang@v1
        with:
          cc: 0

      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Configure MinGW CMake
        if: matrix.compiler == 'mingw'
        run: cmake --preset=test -G Ninja -D CMAKE_C_COMPILER=${{steps.setup_mingw.outputs.gcc}} -D CMAKE_CXX_COMPILER=${{steps.setup_mingw.outputs.gxx}}

      - name: Configure Clang CMake
        if: matrix.compiler == 'clang'
        run: cmake --preset=test -G Ninja -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++

      - name: Configure MSVC CMake
        if: matrix.compiler == 'msvc'
        run: cmake --preset=test -G Ninja

      - name: Build
        run: cmake --build --preset=debug -j %NUMBER_OF_PROCESSOR%

      - name: Test
        working-directory: ${{github.workspace}}/build/debug
        run: ctest --extra-verbose -C Debug -L CLI
