name: Windows Debug Build & Tests

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Setup OpenGL Drivers
        uses: ssciwr/setup-mesa-dist-win@v2

      - name: Configure CMake
        run: cmake --preset=test

      - name: Build
        run: cmake --build --preset=debug -- /maxcpucount

      - name: Test
        working-directory: build/debug
        run: ctest --extra-verbose -C Debug -L CLI
